server {
  listen 80 default_server;
  server_name matrix-homeline.chilllab.dev;

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name matrix-homeline.chilllab.dev;

  ssl_certificate /etc/nginx/ssl/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/privkey.pem;

  # Matrix API -> Synapse
  location ^~ /_matrix {
    proxy_pass http://matrix-synapse:8008;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 120s;
    client_max_body_size 50m;
  }

  location ^~ /_synapse/client {
    proxy_pass http://matrix-synapse:8008;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 120s;
    client_max_body_size 50m;
  }

  # Only needed for "synapse-admin".
  # If the service is removed, better to close access to this path
  location ^~ /_synapse/admin {
    proxy_pass http://matrix-synapse:8008;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 120s;
    client_max_body_size 50m;
  }

  # Synapse Admin UI
  location /admin/ {
    proxy_pass http://synapse-admin:80/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # Everything else -> Element
  location / {
    proxy_pass http://matrix-element:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location ^~ /livekit/jwt/ {
    proxy_pass http://matrix-lk-jwt:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # LiveKit (websocket)
  location ^~ /livekit/sfu/ {
    proxy_pass http://matrix-livekit:7880/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_send_timeout 120;
    proxy_read_timeout 120;
    proxy_buffering off;

    proxy_set_header Accept-Encoding gzip;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  # 3. CRITICAL: Twirp API for Room Creation
  location ^~ /twirp/ {
      proxy_pass http://matrix-livekit:7880; # No trailing slash here
      proxy_set_header Host $host;
  }

  # Enable video calls. Element X app requires these urls available to point to RTC server 
  location = /.well-known/matrix/client {
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
    return 200 '{
      "m.homeserver": {
        "base_url": "https://matrix-homeline.chilllab.dev"
      },
      "org.matrix.msc4143.rtc_foci": [
        {
          "type": "livekit",
          "livekit_service_url": "https://matrix-homeline.chilllab.dev/livekit/jwt"
        }
      ]
    }';
  }

  location = /.well-known/matrix/server {
    default_type application/json;
    return 200 '{
      "m.server": "matrix-homeline.chilllab.dev:443"
    }';
  }
}
